name: KMMBridge Publish Release
on: workflow_dispatch

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
    secrets:
      PODSPEC_SSH_KEY: glpat-yWUq5iZMqx8yF-z_xess